mpc:
  # 当前节点的初始编号
  id: 0
  # 总共节点数目
  total: 3
  # 所有节点的 ip 地址
  calculators: 127.0.0.1:8080,127.0.0.1:8081,127.0.0.1:8082
  # 数据提供者的 ip 地址
  providers: 127.0.0.1:9090,127.0.0.1:9091
  field:
    alpha: 2
    k: 13
server:
  port: 8080
